CREATE USER 'new_user'@'localhost' IDENTIFIED BY 'password123456'; 
GRANT ALL PRIVILEGES ON *.* TO 'new_user'@'localhost'; 
FLUSH PRIVILEGES; 

CREATE TABLE Employee ( 
EMPNO INT, 
ENAME VARCHAR(50), 
JOB VARCHAR(50), 
MANAGER_NO INT, 
SAL DECIMAL(10, 2), 
COMMISSION DECIMAL(10, 2) 
);

INSERT INTO Employee VALUES (1, 'John Doe', 'Manager', NULL, 5000.00, 1000.00);
INSERT INTO Employee VALUES (2, 'Jane Smith', 'Developer', 1, 4000.00, NULL);
INSERT INTO Employee VALUES (3, 'Alice Johnson', 'Salesperson', 1, 3000.00, 500.00);

ALTER TABLE Employee ADD PRIMARY KEY (EMPNO);

ALTER TABLE Employee 
MODIFY ENAME VARCHAR(50) NOT NULL, 
MODIFY JOB VARCHAR(50) NOT NULL, 
MODIFY SAL DECIMAL(10,2) NOT NULL;

INSERT INTO Employee values(1,NULL,'intern',2,NULL,NULL); 
